language: node_js
node_js:
  - '4.4'

cache:
  directories:
    - node_modules

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g bower karma gulp jshint firebase-tools
  - npm install
  - bower install
  - sleep 1 # give server time to start

script:
  - gulp test

after_success:
  - gulp build
  - firebase deploy --project project-1936942649442708634 --token $FIREBASE_TOKEN