language: node_js
node_js:
  - '4.4'

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g bower karma gulp jshint firebase-tools
  - npm install
  - bower install
  - sleep 1 # give server time to start

script:
  - gulp test

after_success:
  - gulp build
  - firebase deploy --token $FIREBASE_TOKEN